# Site Settings
title: Start Jekyll
email: taniarascia@gmail.com
description: >
  A guide to getting started with Jekyll.
# baseurl: '/startjekyll'
baseurl:
url: 'https://thomas-hy-zheng.github.io'
twitter_username: taniarascia
github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM